# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.2
          cache: "npm"
      - run: npm i
      - name: Build 
        if: always()
        run: npm run build
      - run: npm run cypress:run
